name: 'k3s + jenkins + prometheus'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'k3s + jenkins + prometheus'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_is_local_setup: false
          TF_VAR_domain: ${{ vars.TF_VAR_DOMAIN }}
          TF_VAR_k3s_token: ${{ secrets.TF_VAR_K3S_TOKEN }}
          TF_VAR_private_key: ${{ secrets.TF_VAR_PRIVATE_KEY }}
          TF_VAR_private_key_path: ${{ vars.TF_VAR_PRIVATE_KEY_PATH }}
          TF_VAR_ssl_cert: ${{ secrets.TF_VAR_SSL_CERT }}
          TF_VAR_ssl_key: ${{ secrets.TF_VAR_SSL_KEY }}
